Repository Todak-Padak/TodakTodak_frontend, pull requests merged in 2024-10, with the labels that each got.

#21 FE: 마이페이지 디폴트 이미지 수정
  src/views/member/MyPage.vue
Labels: 🧹refactor

#23 FE: 마이페이지 프로필 이미지 수정
  src/views/member/MyPage.vue
Labels: 🍀 enhancement

#29 Feat/is 134 커뮤니티 리스트(기초), 게시글 디테일 화면(게시글 신고 기능까지)
  package-lock.json
  package.json
  src/App.vue
  src/assets/comment.png
  src/assets/community.png
  src/assets/delete.png
  src/assets/like.png
  src/assets/pencil.png
  src/assets/report.png
  src/main.js
  src/router/communityRouter.js
  src/router/index.js
  src/views/community/ReportCreate.vue
  src/views/community/communityDetail.vue
  src/views/community/communityList.vue
  src/views/report/ReportCreate.vue
  src/views/untact/UntactTreatList.vue
Labels: ✨ feature

#30 Feat/is 154 커뮤니티 신고, 권한 설정 및 그에 따른 alert 알림
  src/components/header/HeaderComponent.vue
  src/views/community/ReportComment.vue
  src/views/community/ReportPost.vue
  src/views/community/communityDetail.vue
Labels: ✨ feature

#31 feat/IS-155/:communityList 페이지 구현
  src/views/community/communityList.vue
Labels: ✨ feature

#33 feat: 알림 코드 전체적인 수정 및 카프카 오류 해결, 자녀 공유 알림 추가, 알림 클릭시 읽음 처리와 해당 페이지 이동 로직
  public/firebase-messaging-sw.js
  src/App.vue
  src/components/header/HeaderComponent.vue
Labels: enhancement

#35 Feat/IS-164 게시글 리스트, 게시글 상세 v-card width 수정, 게시글 작성 페이지
  src/router/communityRouter.js
  src/views/community/PostCreate.vue
  src/views/community/communityDetail.vue
  src/views/community/communityList.vue
Labels: ✨ feature

#37 feat: 비대면 결제 이후 결제 로직 추가!
  src/components/pay/SinglePaymentComponent.vue
  src/views/untact/UntactChatRoom.vue
Labels: 🍀 enhancement

#38 feat: 캘린더 작업 1차 -> 예약 리스트
  package-lock.json
  package.json
  src/components/header/HeaderComponent.vue
  src/router/memberRouter.js
  src/views/member/FullCal.vue
Labels: 🍀 enhancement

#51 feat/IS-190 : 병원디테일 진료정보탭 + 의사 정보 디테일 모달
  src/views/hospital/HospitalDetail.vue
  src/views/hospital/HospitalIntro.vue
  src/views/hospital/HospitalList.vue
  src/views/hospital/HospitalMedicalInfo.vue
Labels: ✨ feature

#52 feat: 공유 캘린더
  package-lock.json
  package.json
  public/index.html
  src/views/member/FullCal.vue
Labels: ✨ feature

#57 feat/IS-202 : 병원디테일 리뷰탭 - 리뷰리스트 페이지 추가, 스케쥴예약/오늘예약 스타일 수정
  src/router/reservationRouter.js
  src/views/hospital/HospitalDetail.vue
  src/views/hospital/HospitalIntro.vue
  src/views/hospital/HospitalMedicalInfo.vue
  src/views/hospital/HospitalReviews.vue
  src/views/reservation/ReservationImmediate.vue
  src/views/reservation/ReservationScheduled.vue
Labels: ✨ feature

#59 FE: 알림 리스트 및 리다이렉트 및 읽음 여부 처리
  src/router/memberRouter.js
Labels: ✨ feature

#65 Feat/is 225 게시글 상세 프사 추가, 제목 내용 동일 위치, 게시글 수정 페이지
  src/router/communityRouter.js
  src/router/mypageRouter.js
  src/views/community/PostUpdate.vue
  src/views/community/communityDetail.vue
  src/views/community/communityList.vue
Labels: ✨ feature

#69 Fix/is 230 게시글 상세 최종
  src/assets/padak.jpg
  src/views/community/communityDetail.vue
Labels: 🚧 fix

#70 feat: 멤버 리스트 검색 및 필터
  src/views/admin/MemberList.vue
  src/views/member/FullCal.vue
Labels: 🚧 fix

#73 feat: 관리자 페이지(병원리스트, 병원디테일, 병원 요청 승인)
  src/router/adminRouter.js
  src/views/admin/HospitalAdminDetail.vue
  src/views/admin/HospitalAdminList.vue
  src/views/admin/MemberList.vue
Labels: ✨ feature

#74 Feat/is 232 병원 내 의사 목록 페이지, 의사 등록/삭제 모달
  package-lock.json
  package.json
  src/assets/doctor.png
  src/main.js
  src/router/doctorRouter.js
  src/router/hospitalRouter.js
  src/store/index.js
  src/views/hospital/DoctorCreateModal.vue
  src/views/hospital/DoctorDeleteModal.vue
  src/views/hospital/DoctorDetail.vue
  src/views/hospital/DoctorRegister.vue
Labels: ✨ feature

#76 FE: 정기결제 데이터 수정
  src/views/payment/SubPayment.vue
Labels: 🚧 fix

#77 Feat/IS-247 병원별 의사 목록, 의사 상세 화면, 의사 정보 수정화면
  src/router/hospitalRouter.js
  src/views/community/PostCreate.vue
  src/views/hospital/DoctorDetail.vue
  src/views/hospital/DoctorEdit.vue
  src/views/hospital/DoctorRegister.vue
Labels: ✨ feature

#79 feat: 정기결제 및 병원 관리자 role 추가, 새로운 토큰 발급 및 갱신
  public/index.html
  src/components/header/HeaderComponent.vue
  src/components/pay/SubPaymentComponent.vue
  src/router/hospitalRouter.js
  src/router/index.js
  src/router/memberRouter.js
  src/views/hospital/HospitalAdminCreate.vue
  src/views/member/HospitalAdminLogin.vue
  src/views/payment/PayProcess.vue
  src/views/payment/SubPayment.vue
Labels: ✨ feature

#84 feat: 병원 어드민 회원가입 페이지 완료(모달창) 및 결제 모달 끝
  src/components/pay/SubPaymentComponent.vue
  src/views/hospital/HospitalAdminCreate.vue
  src/views/member/UpdateMember.vue
  src/views/payment/SubPayment.vue
Labels: 🚧 fix

#87 Feat/is 266
  src/router/adminRouter.js
  src/views/admin/CsList.vue
Labels: 🚧 fix

#90 Fix/is 250 의사 근무시간 설정
  src/components/sidebar/MyPageSideBar.vue
  src/store/index.js
  src/views/hospital/DoctorDetail.vue
  src/views/hospital/DoctorEdit.vue
  src/views/hospital/DoctorRegister.vue
Labels: 🚧 fix

#93 feat: 병원 어드민 (병원 관리 페이지)
  src/components/header/HeaderComponent.vue
  src/router/hospitalAdmin.js
  src/router/index.js
  src/views/hospital/HospitalAdminCreate.vue
  src/views/hospitalAdmin/HospitalDetail.vue
Labels: 🚧 fix

#98 feat: 병원어드민 병원영업시간 관리
  package-lock.json
  package.json
  src/plugins/vuetify.js
  src/router/hospitalAdmin.js
  src/views/hospitalAdmin/HospitaAdminHospitallDetail.vue
  src/views/hospitalAdmin/HospitalTimeDetail.vue
Labels: ✨ feature

#102 feat: 캘린더 레이아웃
  src/router/mypageRouter.js
  src/views/member/FullCal2.vue
  src/views/member/FullCal3.vue
  src/views/member/UpdateMember.vue
Labels: ✨ feature

#105 feat: 라우팅 수정
  src/components/carousel/HospitalCarousel.vue
  src/components/footer/FooterComponent.vue
  src/components/header/HeaderComponent.vue
  src/components/header/HospitalAdminHeaderComponent.vue
  src/components/header/MemberHeaderComponent.vue
  src/components/sidebar/HospitalAdminSideBar.vue
  src/components/sidebar/PadakAdminSideBar.vue
  src/router/communityRouter.js
  src/router/doctorRouter.js
  src/router/hospitalRouter.js
  src/router/index.js
  src/router/memberRouter.js
  src/router/paymentRouter.js
  src/router/reservationRouter.js
  src/router/todakRouter.js
  src/router/untactRouter.js
  src/views/MainPage.vue
  src/views/community/communityDetail.vue
  src/views/community/communityList.vue
  src/views/doctor/DoctorUntactReservation.vue
  src/views/hospital/HospitalAdminCreate.vue
  src/views/hospital/HospitalDetail.vue
  src/views/hospital/HospitalList.vue
  src/views/hospital/HospitalList22.vue
  src/views/hospital/HospitalSignIn.vue
  src/views/member/AdminLoginPage.vue
  src/views/member/FindEmailPage.vue
  src/views/member/FindPasswordPage.vue
  src/views/member/FullCal3.vue
  src/views/member/HospitalAdminLogin.vue
  src/views/member/LoginPage.vue
  src/views/member/ResetPasswordPage.vue
  src/views/mypage/MyReservation.vue
  src/views/untact/UntactChatRoom.vue
  src/views/untact/UntactDetail.vue
  src/views/untact/UntactTreatList.vue
  src/views/untact/UntactTreatList2.vue
Labels: 🍀 enhancement

#106 feat: 병원어드민 회원가입, 로컬스토리지 수정
  src/components/header/HospitalAdminHeaderComponent.vue
  src/components/header/MemberHeaderComponent.vue
  src/router/memberRouter.js
  src/views/hospital/HospitalAdminCreate.vue
  src/views/member/AdminLoginPage.vue
Labels: 🚧 fix

#108 Fix/is 299 fix: 의사 삭제 버튼 UI 수정 및의사 프로필 사진 선택 불가로 수정
  src/views/hospital/DoctorRegister.vue
Labels: 🚧 fix

#110 feat: 자잘한 수정
  src/components/footer/FooterComponent.vue
  src/components/sidebar/MyPageSideBar.vue
  src/views/hospital/HospitalAdminCreate.vue
  src/views/hospitalAdmin/HospitaAdminHospitallDetail.vue
  src/views/member/LoginPage.vue
  src/views/member/UpdateMember.vue
Labels: 🚧 fix

#112 feat: 병원어드민 병원 디테일 페이지(병원 디폴트 이미지, 주소(동) 이슈 해결
  src/components/pay/SubPaymentComponent.vue
  src/views/hospitalAdmin/HospitaAdminHospitallDetail.vue
  src/views/member/UpdateMember.vue
Labels: 🚧 fix

#114 feat: 알림 드롭다운리스트, 마이페이지 프로필 사진 수정, 어드민 멤버 리스트 주소 수정 등
  src/components/header/HeaderComponent.vue
  src/components/header/MemberHeaderComponent.vue
  src/views/MainPage.vue
  src/views/admin/MemberList.vue
  src/views/child/ChildCreateModal.vue
  src/views/member/HospitalAdminLogin.vue
  src/views/member/LoginPage.vue
  src/views/mypage/MyPage.vue
Labels: ✨ feature

#118 FE: 병원어드민 병원 리스트 병원 삭제처리
  src/views/admin/HospitalAdminList.vue
  src/views/hospitalAdmin/HospitalTimeDetail.vue
Labels: 🚧 fix

#123 FE: 다크모드 삭제 및 권한관리
  src/components/header/MemberHeaderComponent.vue
  src/main.js
  src/plugins/vuetify.js
  src/router/index.js
  src/views/todak/AdminStatistics.vue
Labels: 🚧 fix

#130 FE: 로그인 권한 관리 및 예외 처리 구체화
  src/views/member/AdminLoginPage.vue
  src/views/member/HospitalAdminLogin.vue
  src/views/member/LoginPage.vue
Labels: 🚧 fix

#141 Fix/IS-361 대댓글 신고 수정
  README.md
  src/views/community/ReportComment.vue
  src/views/community/ReportReply.vue
  src/views/community/communityDetail.vue
Labels: 🚧 fix

#149 feat: 파이어베이스 설정 및 관련 코드 전체 수정
  public/firebase-messaging-sw.js
  src/App.vue
  src/components/header/MemberHeaderComponent.vue
  src/firebase.js
  src/main.js
  src/views/hospital/HospitalDetail.vue
Labels: 🚧 fix

#158 FE: 카카오 로그인 배포 설정
  src/components/header/MemberHeaderComponent.vue
  src/router/memberRouter.js
Labels: 🚧 fix

#161 FE: ws
  src/views/chat/CsChat.vue
  src/views/todak/AdminCsCenter.vue
Labels: ✨ feature

#163 FE: 채팅 오류 수정
  src/views/chat/CsChat.vue
Labels: ✨ feature

#165 FE: 채팅 수정중(중복 메시지)
  src/views/chat/CsChat.vue
Labels: ✨ feature

#167 FE: 병원로그인 에러 메시지 수정
  src/views/member/HospitalAdminLogin.vue
Labels: 🍀 enhancement
